const TEAM_ISO = {
  Argentina: 'ar',
  Australia: 'au',
  Austria: 'at',
  Belgium: 'be',
  Brazil: 'br',
  Canada: 'ca',
  Chile: 'cl',
  China: 'cn',
  Colombia: 'co',
  Croatia: 'hr',
  'Czech Republic': 'cz',
  Czechia: 'cz',
  Denmark: 'dk',
  Ecuador: 'ec',
  Egypt: 'eg',
  England: 'gb-eng',
  France: 'fr',
  Germany: 'de',
  Ghana: 'gh',
  Greece: 'gr',
  Iran: 'ir',
  Italy: 'it',
  Japan: 'jp',
  Mexico: 'mx',
  Morocco: 'ma',
  Netherlands: 'nl',
  Nigeria: 'ng',
  Norway: 'no',
  Poland: 'pl',
  Portugal: 'pt',
  Qatar: 'qa',
  'Saudi Arabia': 'sa',
  Scotland: 'gb-sct',
  Senegal: 'sn',
  Serbia: 'rs',
  'South Africa': 'za',
  'South Korea': 'kr',
  Spain: 'es',
  Sweden: 'se',
  Switzerland: 'ch',
  Tunisia: 'tn',
  Turkey: 'tr',
  Uruguay: 'uy',
  USA: 'us',
  'United States': 'us',
  Wales: 'gb-wls',
  'Bosnia and Herzegovina': 'ba',
  'Bosnia-Herzegovina': 'ba',
  'Bosnia & Herzegovina': 'ba',
  Cameroon: 'cm',
  'Costa Rica': 'cr',
  'Ivory Coast': 'ci',
  Jamaica: 'jm',
  Panama: 'pa',
  Paraguay: 'py',
  Peru: 'pe',
  'New Zealand': 'nz',
  Ukraine: 'ua',
  Hungary: 'hu',
  Romania: 'ro',
  Algeria: 'dz',
  Bolivia: 'bo',
  Venezuela: 've',
  Haiti: 'ht',
  Iraq: 'iq',
  Jordan: 'jo',
  Uzbekistan: 'uz',
  'DR Congo': 'cd',
  Curaçao: 'cw',
  Curacao: 'cw',
  'Cape Verde': 'cv',
};

const TEAM_ES = {
  'South Korea': 'Corea del Sur',
  'Czech Republic': 'República Checa',
  Czechia: 'Chequia',
  'South Africa': 'Sudáfrica',
  'United States': 'Estados Unidos',
  USA: 'Estados Unidos',
  'Bosnia and Herzegovina': 'Bosnia',
  'Bosnia-Herzegovina': 'Bosnia',
  'Bosnia & Herzegovina': 'Bosnia',
  England: 'Inglaterra',
  Germany: 'Alemania',
  Spain: 'España',
  France: 'Francia',
  Brazil: 'Brasil',
  Argentina: 'Argentina',
  Mexico: 'México',
  Japan: 'Japón',
  Netherlands: 'Países Bajos',
  Portugal: 'Portugal',
  Croatia: 'Croacia',
  Switzerland: 'Suiza',
  Canada: 'Canadá',
  Morocco: 'Marruecos',
  Senegal: 'Senegal',
  Uruguay: 'Uruguay',
  Ecuador: 'Ecuador',
  'Saudi Arabia': 'Arabia Saudita',
  Iran: 'Irán',
  Tunisia: 'Túnez',
  Algeria: 'Argelia',
  Ghana: 'Ghana',
  'Ivory Coast': 'Costa de Marfil',
  'DR Congo': 'RD Congo',
  'Cape Verde': 'Cabo Verde',
  Curaçao: 'Curazao',
  Curacao: 'Curazao',
  Haiti: 'Haití',
  Jordan: 'Jordania',
  Uzbekistan: 'Uzbekistán',
  Paraguay: 'Paraguay',
  Panama: 'Panamá',
  Scotland: 'Escocia',
  Norway: 'Noruega',
  Sweden: 'Suecia',
  Australia: 'Australia',
  'New Zealand': 'Nueva Zelanda',
  Qatar: 'Catar',
  Egypt: 'Egipto',
  Iraq: 'Irak',
  Turkey: 'Turquía',
  Belgium: 'Bélgica',
  Austria: 'Austria',
};

export function translateTeam(name) {
  return TEAM_ES[name] || name;
}

export function getFlagUrl(teamName) {
  const iso = TEAM_ISO[teamName];
  if (iso) return `https://flagcdn.com/w80/${iso}.png`;
  return 'https://flagcdn.com/w80/un.png';
}

export function teamAbbr(teamName) {
  const known = {
    Mexico: 'MEX',
    'South Africa': 'RSA',
    'South Korea': 'KOR',
    'Czech Republic': 'CZE',
    USA: 'USA',
    England: 'ENG',
    'DR Congo': 'COD',
  };
  return known[teamName] || teamName.slice(0, 3).toUpperCase();
}

export function slugifyTeam(name = '') {
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}
